// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBevNuncBr7pBIucndamB0oKXcYtWvsXYQ',
    appId: '1:584601497448:web:f8aee8a4bdf91267bb70dd',
    messagingSenderId: '584601497448',
    projectId: 'giftify-base',
    authDomain: 'giftify-base.firebaseapp.com',
    storageBucket: 'giftify-base.firebasestorage.app',
    measurementId: 'G-3Z1NYEVFEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_JDRX_NyecNFFTH4Hs8QGJlbQXhkphdE',
    appId: '1:584601497448:android:611c40400424cb4dbb70dd',
    messagingSenderId: '584601497448',
    projectId: 'giftify-base',
    storageBucket: 'giftify-base.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrSjjfBeJNirxjlBaefT7aH4ECI2lW85s',
    appId: '1:584601497448:ios:ef4ba3998e9cbc6abb70dd',
    messagingSenderId: '584601497448',
    projectId: 'giftify-base',
    storageBucket: 'giftify-base.firebasestorage.app',
    iosBundleId: 'com.example.giftify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrSjjfBeJNirxjlBaefT7aH4ECI2lW85s',
    appId: '1:584601497448:ios:ef4ba3998e9cbc6abb70dd',
    messagingSenderId: '584601497448',
    projectId: 'giftify-base',
    storageBucket: 'giftify-base.firebasestorage.app',
    iosBundleId: 'com.example.giftify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBevNuncBr7pBIucndamB0oKXcYtWvsXYQ',
    appId: '1:584601497448:web:06c312c357cc0c4cbb70dd',
    messagingSenderId: '584601497448',
    projectId: 'giftify-base',
    authDomain: 'giftify-base.firebaseapp.com',
    storageBucket: 'giftify-base.firebasestorage.app',
    measurementId: 'G-Q5FL74D11C',
  );
}
